### ISSUE TITLE
有关建议

### ISSUE THREAD

**Issue by MonkeyDEcho** [LCTT/comic#61]
漫画都放到一个目录下有点混乱，自己每次想要找篇漫画想要翻译的时候先得确定这篇有没有翻译，有人加上来了没有感觉很繁琐，还有想要合成图片的时候，找半天文件夹，一个个打开有的是没有翻译的，有的是已经发布的，很累！是否可以想TranslateProject那样呢？

**Comment by wxy** [comment]
哎，目前因为一个 URL 的原因，已经没法大幅度修改目录结构了。其实，你从后往前找。。。很多是没翻译的。
