### ISSUE TITLE
消沉的程序员的部分商榷

### ISSUE THREAD

**Issue by wxy** [LCTT/comic#9]
- 消沉的程序员 1
    - “但 … 啥儿” => “啊？什么？”
    - “我是由一个未处理的异常产生的” => “这一切都是由一个未捕获的异常导致的”
- 消沉的程序员 4
    - “我已穷极一生来编写大量的变量了” => “我穷极一生编写了大量的变量”
    - “但是我该对这些所有的变量做些什么呢？！？” => “但是我该怎么处理这些变量呢？！”
- 消沉的程序员 5
    - “程式” => “程序”，两处
    - “不是程式错误，而是一个阻止数据变成 STDERR 的特性” => “那不是程序错误，是个功能特性，它防止数据变成 STDERR……”
    - “我需要换一下我的裤子” => “我要换条裤子（吓尿了）”
- 消沉的程序员 6
    - “然后，交付期限的最后关头，所有的特点变得…” => “然后，当交付期限和‘最后一分钟特性’出现时…”
- 消沉的程序员 7
    - “再主线上” => “在开发主线上”
- 消沉的程序员 11
    - “新陷入” => “陷入”

**Comment by GHLandy** [comment]
Fixed!
